<?php
/**
 * Created by PhpStorm.
 * User: evg
 * Date: 21/09/2019
 * Time: 11:21
 */

namespace common\components\chatWidget;

use yii\base\Widget;

/**
 * Class ChatWidget
 * @package common\components\chatWidget
 */
class ChatWidget extends Widget
{

    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        $this->view->registerAssetBundle(ChatAsset::class);
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function run()
    {
        if (\Yii::$app->user->isGuest) {
            $username = 'guest' . time();
        } else {
            $username = \Yii::$app->user->identity->username;
        }
        return $this->render('index', ['username' => $username]);
    }

}